In [1]:
import torch

In [3]:
arr = torch.arange(1, 26).reshape((5, 5))
arr

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

In [4]:
second_row = arr[1]
second_row

tensor([ 6,  7,  8,  9, 10])

In [5]:
subtensor = arr[1:-1, 1:-1]
subtensor

tensor([[ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])

In [6]:
tall_tensor = arr.reshape((25, 1))
tall_tensor

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]])