In [1]:
import numpy as np

In [3]:
arr = np.arange(25).reshape((5, 5)) + 1
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
second_row = arr[1]
second_row

array([ 6,  7,  8,  9, 10])

In [6]:
submatrix = arr[1:-1, 1:-1]
submatrix

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [7]:
tall_vector = arr.reshape((25, 1))
tall_vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [9]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])