In [1]:
import numpy as np

In [3]:
arr = np.random.randint(0, 9, (4, 4))
arr

array([[1, 0, 2, 5],
       [2, 1, 5, 3],
       [0, 6, 3, 0],
       [5, 6, 1, 1]])

In [4]:
mean_centered = arr - arr.mean()
mean_centered

array([[-1.5625, -2.5625, -0.5625,  2.4375],
       [-0.5625, -1.5625,  2.4375,  0.4375],
       [-2.5625,  3.4375,  0.4375, -2.5625],
       [ 2.4375,  3.4375, -1.5625, -1.5625]])

In [6]:
multiplied = arr * np.array([1, 2, 3, 4])
multiplied

array([[ 1,  0,  6, 20],
       [ 2,  2, 15, 12],
       [ 0, 12,  9,  0],
       [ 5, 12,  3,  4]])

In [7]:
summed = arr.sum(axis=1)
summed

array([ 8, 11,  9, 13])