In [1]:
import torch

In [4]:
arr = torch.randint(0, 9, (4, 4), dtype=torch.float32)
arr

tensor([[6., 7., 7., 8.],
        [8., 7., 4., 6.],
        [0., 0., 6., 4.],
        [1., 1., 3., 2.]])

In [5]:
mean_centered = arr - arr.mean()
mean_centered

tensor([[ 1.6250,  2.6250,  2.6250,  3.6250],
        [ 3.6250,  2.6250, -0.3750,  1.6250],
        [-4.3750, -4.3750,  1.6250, -0.3750],
        [-3.3750, -3.3750, -1.3750, -2.3750]])

In [6]:
multiplied = arr * torch.Tensor([1, 2, 3, 4])
multiplied

tensor([[ 6., 14., 21., 32.],
        [ 8., 14., 12., 24.],
        [ 0.,  0., 18., 16.],
        [ 1.,  2.,  9.,  8.]])

In [8]:
summed = arr.sum(dim=1)
summed

tensor([28., 25., 10.,  7.])