In [1]:
import torch

In [2]:
arr = torch.randint(0, 20, (6, 6))
arr

tensor([[10, 15, 14, 15,  4, 10],
        [ 4,  7, 11,  2,  8,  1],
        [15, 16, 18,  0, 15,  6],
        [ 1, 14, 14,  9, 13,  0],
        [14,  6, 12,  8,  6,  3],
        [10, 16, 16,  4,  6,  6]])

In [3]:
arr[arr % 2 == 0] = -1
arr

tensor([[-1, 15, -1, 15, -1, -1],
        [-1,  7, 11, -1, -1,  1],
        [15, -1, -1, -1, 15, -1],
        [ 1, -1, -1,  9, 13, -1],
        [-1, -1, -1, -1, -1,  3],
        [-1, -1, -1, -1, -1, -1]])

In [4]:
gt10 = arr[arr > 10]
gt10

tensor([15, 15, 11, 15, 15, 13])

In [5]:
diag = arr[torch.arange(6), torch.arange(6)]
diag

tensor([-1,  7, -1,  9, -1, -1])