In [1]:
import numpy as np

In [2]:
arr = np.random.randint(0, 20, (6, 6))
arr

array([[ 1, 18,  1, 17, 10,  9],
       [ 2,  3,  7, 16,  7,  3],
       [18,  7, 11, 15, 15, 19],
       [12, 19,  4,  8,  3, 18],
       [11, 15, 14, 13, 18,  3],
       [ 3, 15, 10,  4, 18,  1]])

In [5]:
arr[arr % 2 == 0] = -1
arr

array([[ 1, -1,  1, 17, -1,  9],
       [-1,  3,  7, -1,  7,  3],
       [-1,  7, 11, 15, 15, 19],
       [-1, 19, -1, -1,  3, -1],
       [11, 15, -1, 13, -1,  3],
       [ 3, 15, -1, -1, -1,  1]])

In [6]:
gt10 = arr[arr > 10]
gt10

array([17, 11, 15, 15, 19, 19, 11, 15, 13, 15])

In [9]:
diag = arr[np.arange(6), np.arange(6)]
diag

array([ 1,  3, 11, -1, -1,  1])