In [1]:
import torch

In [2]:
arr = torch.arange(0, 36, dtype=torch.float32).reshape((6, 6))
arr

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.]])

The unfold op: go to column 0, get 2 right-neighbors taking one unit from each (which is just a cell for 2d case), slide 1 column to the right and repeat

In [7]:
step1 = arr.unfold(1, 3, 1)
step1

tensor([[[ 0.,  1.,  2.],
         [ 1.,  2.,  3.],
         [ 2.,  3.,  4.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 7.,  8.,  9.],
         [ 8.,  9., 10.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [13., 14., 15.],
         [14., 15., 16.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [19., 20., 21.],
         [20., 21., 22.],
         [21., 22., 23.]],

        [[24., 25., 26.],
         [25., 26., 27.],
         [26., 27., 28.],
         [27., 28., 29.]],

        [[30., 31., 32.],
         [31., 32., 33.],
         [32., 33., 34.],
         [33., 34., 35.]]])

The unfold op: go to position/container 0, get 2 deeper neighbors taking one unit from each (which is a row for this 3d case), slide 1 position/container deeper and repeat

In [12]:
step2 = step1.unfold(0, 3, 1).mT
step2

tensor([[[[ 0.,  1.,  2.],
          [ 6.,  7.,  8.],
          [12., 13., 14.]],

         [[ 1.,  2.,  3.],
          [ 7.,  8.,  9.],
          [13., 14., 15.]],

         [[ 2.,  3.,  4.],
          [ 8.,  9., 10.],
          [14., 15., 16.]],

         [[ 3.,  4.,  5.],
          [ 9., 10., 11.],
          [15., 16., 17.]]],


        [[[ 6.,  7.,  8.],
          [12., 13., 14.],
          [18., 19., 20.]],

         [[ 7.,  8.,  9.],
          [13., 14., 15.],
          [19., 20., 21.]],

         [[ 8.,  9., 10.],
          [14., 15., 16.],
          [20., 21., 22.]],

         [[ 9., 10., 11.],
          [15., 16., 17.],
          [21., 22., 23.]]],


        [[[12., 13., 14.],
          [18., 19., 20.],
          [24., 25., 26.]],

         [[13., 14., 15.],
          [19., 20., 21.],
          [25., 26., 27.]],

         [[14., 15., 16.],
          [20., 21., 22.],
          [26., 27., 28.]],

         [[15., 16., 17.],
          [21., 22., 23.],
          [27., 28., 29.]]],


In [5]:
result = step2.mean(dim=(2, 3))
result

tensor([[ 7.,  8.,  9., 10.],
        [13., 14., 15., 16.],
        [19., 20., 21., 22.],
        [25., 26., 27., 28.]])

In [10]:
step1[0]

tensor([[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])