In [1]:
import numpy as np

Original image: pixels may only occupy a narrow range, say [50–150]. The histogram is tall in that band, empty outside.
After equalization: those intensities are “spread out” over the entire [0–255]. Dark pixels are pushed toward 0, bright ones toward 255.
The idea is to maximize contrast by stretching the dynamic range of the image.

[ 50,  52,  52<br />
&nbsp;&nbsp;51,  52,  53<br />
&nbsp;&nbsp;52,  53,  54 ]

- Histogram: values cluster between 50–54.
- Equalization: those 5 gray levels get remapped across 0–255, e.g.
    50 -> 0
    51 -> 64
    52 -> 128
    53 -> 192
    54 -> 255

So the new image spans the full contrast range, even though the original didn’t.

In [2]:
img = np.array([
    [50, 52, 52],
    [51, 52, 53],
    [52, 53, 54]
], dtype=np.uint8)
img

array([[50, 52, 52],
       [51, 52, 53],
       [52, 53, 54]], dtype=uint8)

In [3]:
hist = np.bincount(img.flatten(), minlength=256)
hist

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
cdf = np.cumsum(hist)
cdf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 2, 6, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [7]:
high = 200
low = 50
cdf_norm = cdf / cdf.max()
lookup_table = (cdf_norm * (high - low) + low).astype(np.uint8)
img_eq = lookup_table[img]
img_eq

array([[ 66, 150, 150],
       [ 83, 150, 183],
       [150, 183, 200]], dtype=uint8)

In [8]:
high = 200
low = 50
cdf_min = cdf[cdf > 0][0]
cdf_norm = (cdf - cdf_min) / (cdf.max() - cdf_min)
lookup_table = (cdf_norm * (high - low) + low).astype(np.uint8)
img_eq = lookup_table[img]
img_eq

array([[ 50, 143, 143],
       [ 68, 143, 181],
       [143, 181, 200]], dtype=uint8)