In [145]:
import numpy as np

In [146]:
img = np.array([
    [1, 2, 3, 50, 52, 52, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4],
    [51, 52, 53, 22, 23, 24, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4],
    [52, 53, 54, 108, 109, 110, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4],
    [0, 1, 1, 49, 50, 51, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4],
    [50, 51, 52, 21, 22, 23, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4],
    [51, 52, 53, 107, 106, 105, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4],
    [1] * 14 + [4] * 5,
    [1] * 14 + [4] * 5,
    [1] * 14 + [4] * 5,
    [1] * 14 + [4] * 5,
    [1] * 14 + [4] * 5,
    [1] * 14 + [4] * 5,
    [1] * 14 + [4] * 5,
    [200] * (14 + 5),
    [200] * (14 + 5),
    [200] * (14 + 5),
    [200] * (14 + 5)
], dtype=np.long)
img

array([[  1,   2,   3,  50,  52,  52,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [ 51,  52,  53,  22,  23,  24,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [ 52,  53,  54, 108, 109, 110,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [  0,   1,   1,  49,  50,  51,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [ 50,  51,  52,  21,  22,  23,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [ 51,  52,  53, 107, 106, 105,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4,   4],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   4,   4,   4,   4

In [147]:
hist = np.bincount(img.flatten(), minlength=256)
hist

array([  1, 149,   1,   1,  65,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   1,   2,   2,   1,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   3,   4,
         6,   3,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   1,   1,   1,   1,   1,   1,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

Capacities tell how much space is left in each bin

In [148]:
clip_limit = 2
hist = hist.astype(np.int64, copy=True)
clipped = np.minimum(hist, clip_limit)
clipped

array([1, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [149]:
capacities = clip_limit - clipped

while clipped[clipped < clip_limit].size > 0:
    eligible = np.where(capacities > 0)[0]
    excess = int(hist.sum() - clipped.sum())
    q, r = divmod(excess, clipped[clipped < clip_limit].size)

    if q > 0:
        clipped[eligible] += np.minimum(capacities[eligible], q)
        capacities = clip_limit - clipped
    elif r > 0:
        np.add.at(clipped, eligible[:r], 1)
    else:
        break

hist = clipped

In [150]:
high = 200
low = 50
cdf = np.cumsum(hist)
cdf_min = cdf[cdf > 0][0]
cdf_norm = (cdf - cdf_min) / (cdf.max() - cdf_min)
lookup_table = (cdf_norm * (high - low) + low).astype(np.uint8)
img_eq = lookup_table[img]
img_eq

array([[ 50,  51,  52,  96,  98,  98,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 97,  98,  99,  70,  71,  72,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 98,  99, 100, 129, 130, 131,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 50,  50,  50,  95,  96,  97,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 96,  97,  98,  69,  70,  71,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 97,  98,  99, 128, 128, 127,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53,  53],
       [ 50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,  50,
         50,  53,  53,  53,  53