In [2]:
import numpy as np

In [3]:
img = np.arange(9).reshape((3, 3)) + 1
img

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
def pad_array(array: np.ndarray) -> np.ndarray:
    h_padded = np.vstack((
        np.zeros((array.shape[1],)),
        array
    ))
    hv_padded = np.hstack((
        np.zeros((h_padded.shape[0], 1)),
        h_padded
    ))

    return hv_padded


def box_sum(img: np.ndarray, k: int) -> np.ndarray:
    h, w = img.shape
    size_y = h - k + 1
    size_x = w - k + 1
    cum_cols = np.cumsum(img, axis=0)
    ii = np.cumsum(cum_cols, axis=1)
    ii = pad_array(ii)

    return ii

In [100]:
k = 2
sum = box_sum(img, k)
sum

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  3.,  6.],
       [ 0.,  5., 12., 21.],
       [ 0., 12., 27., 45.]])

In [101]:
strides = np.lib.stride_tricks.as_strided(
    sum,
    shape=(sum.shape[0] - k + 1, sum.shape[1] - k + 1, k, k),
    strides=sum.strides + sum.strides
).astype(np.int64)
strides

array([[[[ 0,  0],
         [ 0,  1]],

        [[ 0,  0],
         [ 1,  3]],

        [[ 0,  0],
         [ 3,  6]]],


       [[[ 0,  1],
         [ 0,  5]],

        [[ 1,  3],
         [ 5, 12]],

        [[ 3,  6],
         [12, 21]]],


       [[[ 0,  5],
         [ 0, 12]],

        [[ 5, 12],
         [12, 27]],

        [[12, 21],
         [27, 45]]]])

In [102]:
elements_for_summing = strides[:, :, [0, k - 1]][:, :, :, [0, k - 1]]
elements_for_summing[:, :, 0, 1] = -elements_for_summing[:, :, 0, 1]
elements_for_summing[:, :, 1, 0] = -elements_for_summing[:, :, 1, 0]
elements_for_summing

array([[[[  0,   0],
         [  0,   1]],

        [[  0,   0],
         [ -1,   3]],

        [[  0,   0],
         [ -3,   6]]],


       [[[  0,  -1],
         [  0,   5]],

        [[  1,  -3],
         [ -5,  12]],

        [[  3,  -6],
         [-12,  21]]],


       [[[  0,  -5],
         [  0,  12]],

        [[  5, -12],
         [-12,  27]],

        [[ 12, -21],
         [-27,  45]]]])

In [54]:
[[12, 16],
 [24, 28]]

[[12, 16], [24, 28]]